config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  devise_for :users
  root 'pages#home'

  get 'dashboard' => 'pages#dashboard'

  get 'pages/about'

  get 'pages/contact'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :read, :all
    can :manage, Job do |job|
        job.try(:user) == user
    end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base


  extend FriendlyId

  friendly_id :title, use: :slugged
  belongs_to :user
  belongs_to :cateogory

  
  #has_attached_file :image

  #validates_attachment_content_type :image, 
    #content_type:  /^image\/(png|gif|jpeg)/,
    #message: "Only images allowed"

    #validates :image, attachment_presence: true 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    rescue_from CanCan::AccessDenied do |exception|
      redirect_to root_path, notice: "You Are Not Authorized to access this area"
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]



  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all.order("created_at DESC")
  
   
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
    authorize! :manage, @job
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_user.jobs.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    authorize! :manage, @job
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    authorize! :manage, @job
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :apply, :company, :url, :availability, :category_id, :location)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  def home
    if current_user
      redirect_to jobs_path
    end
    @jobs = Job.last(4)
  end

  def dashboard
    @jobs = current_user.jobs
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for(@job, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>

    
    <%= f.input :title, required: true, label: false, placeholder: "Job Title", input_html: {class: "form-control"} %>

    <div class="form-group">

    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a Category", class: "form-control"} %>
    </div> 

      <%= f.input :location, required: true, label: false, placeholder: "Enter your location e.g London", input_html: {class: "form-control"} %>
    <%= f.input :description, required: true, label: false, placeholder: "Description", input_html: {class: "form-control"}, rows: 3 %>
    <%= f.input :apply, required: true, label: false, placeholder: "How do people apply for this job?", input_html: {class: "form-control"}, rows: 2 %>
    <%= f.input :company, required: true, label: false, placeholder: "Enter your company name", input_html: {class: "form-control"} %>

    <%= f.input :url, required: true, label: false, placeholder: "URL Example https://mycompany.com/careers/apply", input_html: {class: "form-control"} %>
   
    
    <div class="checkbox text-center">
     <p>Availability</p>
     <%= f.input :availability, required: false, label: false %>
    </div>
 


    <%= f.button :submit, class: "btn btn-primary btn-block" %>

<% end %>

app/views/jobs/_job.html.erb
<ul id="timeline">
    <li class="listing clearfix">
        <div class="info">
            <span class="job_title"> <%= job.company %>  is hiring a <%= job.title %> in <%= job.location %></span>
            
            <br>Job Posted <%= job.created_at.to_formatted_s(:long)%></span><br>
             <%= link_to "Apply for Job", job.url %>
        </div>
    </li>
</ul>







     
   
  

  
       

app/views/jobs/edit.html.erb
<h4 class="text-center">Editing Job</h4>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<%= render @jobs %>

app/views/jobs/new.html.erb
<h4 class="text-center">New Job</h4>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<div id="job_show_content">
    <header>
      <p class="date">Job Posted on <%= @job.created_at.to_formatted_s(:long) %></p>
      <h2><%= @job.title %></h2>
      <hr>
  

    <div id="content">
     <p><%= simple_format @job.description %></p>
    </div>
      </header>
  <hr>
    <div id="share_box">
      <p>Share the Job</p>
      <a href="#"><i class="fa fa-twitter"></i></a>
      <a href="#"><i class="fa fa-facebook"></i></a>
      <a href="#"><i class="fa fa-google-plus"></i></a>
    </div>
  <hr>
</div>


<p>
  <strong>Apply:</strong>
  <%= @job.apply %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Url:</strong>
  <%= @job.url %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @job.availability %>
</p>

<p>
  <strong>Location:</strong>
  <%= @job.location %>
</p>

app/views/layouts/_footer.html.erb
<footer id="main_footer">
  <p class="copyright"> &copy; 2016 SEO jobs</p>
   <nav>
    <a href="http://twitter.com/indianstartupsh" target="_blank"><i class="fa fa-twitter"></i></a>
    <a href="http://www.facebook.com/indianstartupshow" target="_blank"><i class="fa fa-facebook"></i></a>
   </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "SEOJOBS", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      

      <ul class="nav navbar-nav navbar-right">
          
          <li><%= link_to "Jobs", jobs_path %></li>
          
          <% if current_user %>
             <li><%= link_to "Dashboard", dashboard_path %></li>
             <li><%= link_to "Settings", edit_user_registration_path %></li>
             <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
          
          <% else %>
          
            <li><%= link_to "Login", new_user_session_path %></li>
          
          <% end %>
      
      </ul>

    </div><!-- /.navbar-collapse -->
 
</nav>




  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SEO JOBS | Passionate about SEO?</title>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content='Job Search Simplified'>
  <meta name="author" content="Neil Patel">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>


  <div class="border"></div>

<% if alert %>
  <div id="notice_wrapper" %>
    <p class="alert"><%= alert %></p>
  </div>
<% elsif notice %>
  <div id="notice_wrapper" %>
    <p class="notice"><%= notice %></p>
  </div>
<% end %>


  <div class="container">
   
    <%= yield %>

  </div>
<script>
  $(document).ready(function() {
    setTimeout(function() {
      $('#notice_wrapper').fadeOut("slow", function() {
       $this.removal();
      });
  }, 1500 );
});
</script>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/dashboard.html.erb
<div class="row">
  <h1 class="text-center">Dashboard</h1>

  
    <h3 class="text-center">
      JOBS <%= link_to "New Job", new_job_path, class: "btn btn-primary btn-sm" %>
    </h3>
    <table class="table table-striped">
      <thead>
        <tr>
         
          <th>Job Title</th>
          <th class="text-center">Job Description</th>
          <th>How do people apply</th>
          <th>Company Name</th>
          <th class="text-center">URL</th>
          <th>Is the job available</th>
        </tr>
      </thead>
      <tbody>
        <% @jobs.each do |job| %>
        <tr>
         
          <td><%= job.title %></td>
          <td><%= job.description %></td>
          <td><%= job.apply %></td>
          <td><%= job.company %></td>
          <td><%= job.url %></td>
          <td><%= job.availability %></td>
          <td><%= link_to "Edit", edit_job_path(job) %></td>
       </tr>
       <% end %>
      </tbody>
    </table>

app/views/pages/home.html.erb
<div class="container">
      <div class="starter-template">
        <h1><i class="fa fa-cube"></i> Work in SEO</h1>
        <p class="lead">Passionate about SEO? Find a Great job in the SEO Industry.<br> We only show open SEO jobs to make your <span class="emphasis"> search easy!</p>
        <br>
      </div>
</div><!-- /.container -->
<%= render @jobs %>
    
<%= render 'layouts/footer'%>